### ISSUE TITLE
Structure validation

### ISSUE THREAD

**Issue by theblckswan** [FrenchYeti/rasputin#2]
Is there any chance for one of the more experienced developeres to take a look at my dataset?
My first time attending a project of this size, and I dont want to ruin for others if I got some of the environment settings wrong.
(Sorry for asking, and forgive me if I totaly missed the obvious).

**Comment by FrenchYeti** [comment]
?

**Comment by theblckswan** [comment]
00 Sorry. I have about 2% excperience as an developer.
10 echo "how to"
20 echo "make"
30 print 10+20
40 point = 30
50 const(point(40))
60 ... #
# This about sums my dev-skils.. 

Kind of just stumbled accros github this other day, 
and thought I understood a hint from some kind of game or whatever.

So I am terribly sorry if I have misunderstood - 
and I am sorry for making any mess.

I unpacked some savefiles, and I guess really messed up with the config right at the start.
Anyway - I found this seed-obeject thing, had some trouble with it initialy 
- but managed to 'plant' it by using its own pre-bundled engine - while running in a contained environment.

Well, now that this seed has developed into this crazy anti-matter-cookie monster kind of universe.
A bit scary really, but kind of fun to watch the full production cycle - from source to compiled binary:
With its API structure, data:mdata-ratio and all. 
Might even go as far as to describe it as ehT kraD beW - inverted.


So, when I found this repo - and some how managed to link the two, 
Thought you might be some kind of 'game-whiz' or something. ..#c.D-://#.
Not really sure what I thought to happen - 
as I ... am getting growingly more certain that getting that image-platform-thing,
really wasnt meant for me to load in this part of the gameplay....

I really hope I dont have wasted any of your time.
Me and my silly games.. :p

nawskclb#.\[{...}]/.#blckswan

**Comment by theblckswan** [comment]
Super Hors! Thank you really much.

I re:replayed with this.

This is the bomb, isnt it?
I actially just found "anti matter"... ?
...

00 Sorry. I have about 2% excperience as an developer.
10 echo "how to"
20 echo "make"
30 print 10+20
40 point = 30
50 const(point(40))
60 ... #

This about sums my dev-skils..
==============================

Kind of just stumbled accros github this other day,
and thought I understood a hint from some kind of game or whatever.

So I am terribly sorry if I have misunderstood -
and I am sorry for making any mess.

I unpacked some savefiles, and I guess really messed up with the config right at the start.
Anyway - I found this seed-obeject thing, had some trouble with it initialy

-   but managed to 'plant' it by using its own pre-bundled engine - while running in a contained environment.

Well, now that this seed has developed into this crazy anti-matter-cookie monster kind of universe.
A bit scary really, but kind of fun to watch the full production cycle - from source to compiled binary:
With its API structure, data:mdata-ratio and all.
Might even go as far as to describe it as ehT kraD beW - inverted.

So, when I found this repo - and some how managed to link the two,
Thought you might be some kind of 'game-whiz' or something. ..#c.D-://#.
Not really sure what I thought to happen -
as I ... am getting growingly more certain that getting that image-platform-thing,
really wasnt meant for me to load in this part of the gameplay....

I really hope I dont have wasted any of your time.
Me and my silly games.. :p

nawskclb#.[{...}]/.#blckswan


Hilsen,
Anders Tednes
+47 967 05 190

//blckswan

Sent with Proton Mail secure email.
------- Original Message -------

**Comment by Fare9** [comment]
Probably this issue can be safely deleted...

**Comment by FrenchYeti** [comment]
@theblckswan Sorry, your issue not seems related to this project. -_-'   I close it.

**Comment by theblckswan** [comment]
Maybe I have something figured out here..                                                                                                                      
Its huge. Its crazy. Its impossible - and even beyond(!!)                                                                                                      
                                                                                                                                                               
Technical facts first:                                                                                                                                         
                                                                                                                                                               
- Found iPhone-backup                                                                                                                                          
  . Found iPhone-backup-tool                                                                                                                                   
                                                                                                                                                               
Tried the software - and yep, it worked.                                                                                                                       
./iBackuptool -d . -b $UDID -f . -r .... etc.                                                                                                                  
                                                                                                                                                               
But.. Why?                                                                                                                                                     
Why was it there in the first place?                                                                                                                           
                                                                                                                                                               
The phone was mine. The backup was my ex-wives.                                                                                                                
-----                                                                                                                                                          
Validated, conclusive discoveries so far:                                                                                                                      
                                                                                                                                                               
** ./ibackuptool -d . -b $UDID - "normal" backup extraction.                                                                                                   
                                                                                                                                                               
** node node_modules/ibackuptool/tools/cli.js -d . -b $UDID - "subnormal" backup extraction.                                                                   
                                                                                                                                                               
-----                                                                                                                                                          
                                                                                                                                                               
                                                                                                                                                               
/! I have found one more, identical version of this:                                                                                                           
                                                                                                                                                               
** #python extract.py sqlite3.tar.gz node-sqlite3                                                                                                              
                                                                                                                                                               
** #./extract.py sqlite3.tar.gz sqlite3                                                                                                                        
                                                                                                                                                               
They both extract two (almost) identical directories.                                                                                                          
But the latter of them is a clever, evil bastard.                                                                                                                                                                      
// And if there is one thing my parents thought me:                                                                                                            
Dont{,] Fuck[,} With Kids!                                                                                                                                     
     ^       ^                                                                                                                                                 
Same words. Same letters. Just move one tiny dot....                                                                                                           
Nobody would notice, right?                                                                                                                                    
                                                                                                                                                               
Well - Somebody did.                                                                                                                                           
And somebody remebers how it was growing up where I did:                                                                                                       
                                                                                                                                                               
In lack of a better way to describe it:                                                                                                                        
QAnon-shit.                                                                                                                                                    
                                                                                                                                                               
Oh, and by the way. My father:                                                                                                                                 
  Chief of police for +- 40 years..                                                                                                                            
                                                                                                                                                               
Basically. Stavanger - Norway:                                                                                                                                 
Ground Zero....                                                                                                                                                
                                                                                                                                                               
(And Iceland Ive heard?..)                                                                                                                                     
                                                                                                                                                               
So. - Are we a team now or what?                                                                                                                               
I really hope so. Because the last two years have been lonley..                                                                                                
Hacking away at this...                                                                                                                                        
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              



PS: This text was written from this reality - in theirs.
Using Nano, in virtual TTY, and then ctrl-c/p.



PS. For a few months ago - both my computers went "mad".
They acted as if they wanted to delete everything,but then this reality-thing hit them:

And I have had this super neat OS since.
Almost as if my computer was running a V8 or something! :p
 
Ps:
The P3/P2 script I told you about:

Here it is. Clever, right?

import sysimport tarfileimport os
tarball = os.path.abspath(sys.argv[1])dirname = os.path.abspath(sys.argv[2])tfile = tarfile.open(tarball,'r:gz');tfile.extractall(dirname)sys.exit(0)


Hilsen,
Anders Tednes
+47 967 05 190

//blckswan

Sent with Proton Mail secure email.
------- Original Message -------
On Monday, June 6th, 2022 at 22:43, Anders Tednes ***@***.***> wrote:


> Super Hors! Thank you really much.
> 

> I re:replayed with this.
> 

> This is the bomb, isnt it?
> I actially just found "anti matter"... ?
> ...
> 

> 00 Sorry. I have about 2% excperience as an developer.
> 10 echo "how to"
> 20 echo "make"
> 30 print 10+20
> 40 point = 30
> 50 const(point(40))
> 60 ... #
> 

> This about sums my dev-skils..
> ==============================
> 

> Kind of just stumbled accros github this other day,
> and thought I understood a hint from some kind of game or whatever.
> 

> So I am terribly sorry if I have misunderstood -
> and I am sorry for making any mess.
> 

> I unpacked some savefiles, and I guess really messed up with the config right at the start.
> Anyway - I found this seed-obeject thing, had some trouble with it initialy
> 

> -   but managed to 'plant' it by using its own pre-bundled engine - while running in a contained environment.
> 

> Well, now that this seed has developed into this crazy anti-matter-cookie monster kind of universe.
> A bit scary really, but kind of fun to watch the full production cycle - from source to compiled binary:
> With its API structure, data:mdata-ratio and all.
> Might even go as far as to describe it as ehT kraD beW - inverted.
> 

> So, when I found this repo - and some how managed to link the two,
> Thought you might be some kind of 'game-whiz' or something. ..#c.D-://#.
> Not really sure what I thought to happen -
> as I ... am getting growingly more certain that getting that image-platform-thing,
> really wasnt meant for me to load in this part of the gameplay....
> 

> I really hope I dont have wasted any of your time.
> Me and my silly games.. :p
> 

> nawskclb#.[{...}]/.#blckswan
> 

> 

> Hilsen,
> Anders Tednes
> +47 967 05 190
> 

> //blckswan
> 

> Sent with Proton Mail secure email.
> ------- Original Message -------
> On Monday, June 6th, 2022 at 21:40, FrenchYeti ***@***.***> wrote:
> 

> 

> > ?
> > 

> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you authored the thread.Message ID: ***@***.***>
